services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: simulador-backend
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./backend/app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1
    depends_on: []

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: simulador-frontend
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    command: npm run dev -- --host 0.0.0.0 --port 3000
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: simulador-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    command: sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - frontend
      - backend

networks:
  default:
    driver: bridge
